############################
# Stage 1 — Build Stage
############################
FROM golang:1.21-alpine AS build

WORKDIR /app

COPY app/ .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o calculator .

############################
# Stage 2 — Runtime Stage
############################
FROM scratch

WORKDIR /app

COPY --from=build /app/calculator .

ENTRYPOINT ["./calculator"]
